spring:
  application:
    name: crm-service
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:coresuite}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    table: flyway_schema_history_crm
    baseline-on-migrate: true
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:root}:${MONGO_PASSWORD:}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:coresuite_crm}?authSource=admin

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
